### ISSUE TITLE
Multiplication followed by dot followed by digit issue

### ISSUE THREAD

**Issue by sebgiroux** [nicklockwood/Expression#11] opened 2017-12-15 18:37 UTC
Hello,

I'm getting the following error:
`13:18:25 ERROR Error in expression X/((16.7-W)*.0000212*Y*Z): Undefined infix operator *.`

I was hoping this commit would fix the issue: https://github.com/nicklockwood/Expression/commit/08fef32a239261ea692aa47aba41f11ea765e1c9 but it doesn't seems like it does.

Probably a simpler expression like 1*.5 would fails as well.

Hopefully this can be fixed somewhat easily.

Thank you

**Comment by nicklockwood** [comment] 2017-12-15 18:43
I suspect that the issue is that it sees *. As a single operator. A space between the * and . Should fix it.

I’ll see if I can come up with a way to disambiguate this in the next release.

**Comment by nicklockwood** [comment] 2017-12-18 18:50
@sebgiroux fixed in 0.9.3

**Closed as completed by nicklockwood** 2017-12-18 18:50 UTC

**Comment by sebgiroux** [comment] 2017-12-19 17:10
@nicklockwood Indeed, it's all good now, thanks a lot!
